version: '3'
services: 
  vue:
    build: 
      context: ./docker/vue
    container_name: myapp-vue
    ports: 
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    tty: true
  go:
    build: 
      context: ./docker/go
    container_name: myapp-go
    ports: 
      - 8082:8082
    volumes: 
      - .:/go/src 
    working_dir: /go/src/app
    tty: true